// flow-typed signature: 1be48d979729abb3f4712bc8b3712126
// flow-typed version: <<STUB>>/j-toker_v0.0.10-beta3/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'j-toker'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'j-toker' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'j-toker/demo/app' {
  declare module.exports: any;
}

declare module 'j-toker/demo/src/scripts/components/access-control' {
  declare module.exports: any;
}

declare module 'j-toker/demo/src/scripts/components/destroy-account' {
  declare module.exports: any;
}

declare module 'j-toker/demo/src/scripts/components/github-banner' {
  declare module.exports: any;
}

declare module 'j-toker/demo/src/scripts/components/login-form' {
  declare module.exports: any;
}

declare module 'j-toker/demo/src/scripts/components/oauth-form' {
  declare module.exports: any;
}

declare module 'j-toker/demo/src/scripts/components/password-reset' {
  declare module.exports: any;
}

declare module 'j-toker/demo/src/scripts/components/password-update' {
  declare module.exports: any;
}

declare module 'j-toker/demo/src/scripts/components/profile-info' {
  declare module.exports: any;
}

declare module 'j-toker/demo/src/scripts/components/registration-form' {
  declare module.exports: any;
}

declare module 'j-toker/demo/src/scripts/components/signout-form' {
  declare module.exports: any;
}

declare module 'j-toker/demo/src/scripts/components/update-account' {
  declare module.exports: any;
}

declare module 'j-toker/demo/src/scripts/main' {
  declare module.exports: any;
}

declare module 'j-toker/demo/src/scripts/mixins/form-state' {
  declare module.exports: any;
}

declare module 'j-toker/demo/src/scripts/mixins/response-modal' {
  declare module.exports: any;
}

declare module 'j-toker/demo/src/scripts/pages/alt-user' {
  declare module.exports: any;
}

declare module 'j-toker/demo/src/scripts/pages/home' {
  declare module.exports: any;
}

declare module 'j-toker/dist/jquery.j-toker' {
  declare module.exports: any;
}

declare module 'j-toker/dist/jquery.j-toker.min' {
  declare module.exports: any;
}

declare module 'j-toker/Gruntfile' {
  declare module.exports: any;
}

declare module 'j-toker/src/j-toker' {
  declare module.exports: any;
}

declare module 'j-toker/test/unit/configuration' {
  declare module.exports: any;
}

declare module 'j-toker/test/unit/destroy-account' {
  declare module.exports: any;
}

declare module 'j-toker/test/unit/email-confirmation' {
  declare module.exports: any;
}

declare module 'j-toker/test/unit/email-sign-in' {
  declare module.exports: any;
}

declare module 'j-toker/test/unit/email-sign-up' {
  declare module.exports: any;
}

declare module 'j-toker/test/unit/o-auth-sign-in' {
  declare module.exports: any;
}

declare module 'j-toker/test/unit/password-reset-confirmation' {
  declare module.exports: any;
}

declare module 'j-toker/test/unit/password-reset-request' {
  declare module.exports: any;
}

declare module 'j-toker/test/unit/querystring' {
  declare module.exports: any;
}

declare module 'j-toker/test/unit/sign-out' {
  declare module.exports: any;
}

declare module 'j-toker/test/unit/token-validation' {
  declare module.exports: any;
}

declare module 'j-toker/test/unit/update-account' {
  declare module.exports: any;
}

declare module 'j-toker/test/unit/update-password' {
  declare module.exports: any;
}

// Filename aliases
declare module 'j-toker/demo/app.js' {
  declare module.exports: $Exports<'j-toker/demo/app'>;
}
declare module 'j-toker/demo/src/scripts/components/access-control.jsx' {
  declare module.exports: $Exports<'j-toker/demo/src/scripts/components/access-control'>;
}
declare module 'j-toker/demo/src/scripts/components/destroy-account.jsx' {
  declare module.exports: $Exports<'j-toker/demo/src/scripts/components/destroy-account'>;
}
declare module 'j-toker/demo/src/scripts/components/github-banner.jsx' {
  declare module.exports: $Exports<'j-toker/demo/src/scripts/components/github-banner'>;
}
declare module 'j-toker/demo/src/scripts/components/login-form.jsx' {
  declare module.exports: $Exports<'j-toker/demo/src/scripts/components/login-form'>;
}
declare module 'j-toker/demo/src/scripts/components/oauth-form.jsx' {
  declare module.exports: $Exports<'j-toker/demo/src/scripts/components/oauth-form'>;
}
declare module 'j-toker/demo/src/scripts/components/password-reset.jsx' {
  declare module.exports: $Exports<'j-toker/demo/src/scripts/components/password-reset'>;
}
declare module 'j-toker/demo/src/scripts/components/password-update.jsx' {
  declare module.exports: $Exports<'j-toker/demo/src/scripts/components/password-update'>;
}
declare module 'j-toker/demo/src/scripts/components/profile-info.jsx' {
  declare module.exports: $Exports<'j-toker/demo/src/scripts/components/profile-info'>;
}
declare module 'j-toker/demo/src/scripts/components/registration-form.jsx' {
  declare module.exports: $Exports<'j-toker/demo/src/scripts/components/registration-form'>;
}
declare module 'j-toker/demo/src/scripts/components/signout-form.jsx' {
  declare module.exports: $Exports<'j-toker/demo/src/scripts/components/signout-form'>;
}
declare module 'j-toker/demo/src/scripts/components/update-account.jsx' {
  declare module.exports: $Exports<'j-toker/demo/src/scripts/components/update-account'>;
}
declare module 'j-toker/demo/src/scripts/main.jsx' {
  declare module.exports: $Exports<'j-toker/demo/src/scripts/main'>;
}
declare module 'j-toker/demo/src/scripts/mixins/form-state.jsx' {
  declare module.exports: $Exports<'j-toker/demo/src/scripts/mixins/form-state'>;
}
declare module 'j-toker/demo/src/scripts/mixins/response-modal.jsx' {
  declare module.exports: $Exports<'j-toker/demo/src/scripts/mixins/response-modal'>;
}
declare module 'j-toker/demo/src/scripts/pages/alt-user.jsx' {
  declare module.exports: $Exports<'j-toker/demo/src/scripts/pages/alt-user'>;
}
declare module 'j-toker/demo/src/scripts/pages/home.jsx' {
  declare module.exports: $Exports<'j-toker/demo/src/scripts/pages/home'>;
}
declare module 'j-toker/dist/jquery.j-toker.js' {
  declare module.exports: $Exports<'j-toker/dist/jquery.j-toker'>;
}
declare module 'j-toker/dist/jquery.j-toker.min.js' {
  declare module.exports: $Exports<'j-toker/dist/jquery.j-toker.min'>;
}
declare module 'j-toker/Gruntfile.js' {
  declare module.exports: $Exports<'j-toker/Gruntfile'>;
}
declare module 'j-toker/src/j-toker.js' {
  declare module.exports: $Exports<'j-toker/src/j-toker'>;
}
declare module 'j-toker/test/unit/configuration.js' {
  declare module.exports: $Exports<'j-toker/test/unit/configuration'>;
}
declare module 'j-toker/test/unit/destroy-account.js' {
  declare module.exports: $Exports<'j-toker/test/unit/destroy-account'>;
}
declare module 'j-toker/test/unit/email-confirmation.js' {
  declare module.exports: $Exports<'j-toker/test/unit/email-confirmation'>;
}
declare module 'j-toker/test/unit/email-sign-in.js' {
  declare module.exports: $Exports<'j-toker/test/unit/email-sign-in'>;
}
declare module 'j-toker/test/unit/email-sign-up.js' {
  declare module.exports: $Exports<'j-toker/test/unit/email-sign-up'>;
}
declare module 'j-toker/test/unit/o-auth-sign-in.js' {
  declare module.exports: $Exports<'j-toker/test/unit/o-auth-sign-in'>;
}
declare module 'j-toker/test/unit/password-reset-confirmation.js' {
  declare module.exports: $Exports<'j-toker/test/unit/password-reset-confirmation'>;
}
declare module 'j-toker/test/unit/password-reset-request.js' {
  declare module.exports: $Exports<'j-toker/test/unit/password-reset-request'>;
}
declare module 'j-toker/test/unit/querystring.js' {
  declare module.exports: $Exports<'j-toker/test/unit/querystring'>;
}
declare module 'j-toker/test/unit/sign-out.js' {
  declare module.exports: $Exports<'j-toker/test/unit/sign-out'>;
}
declare module 'j-toker/test/unit/token-validation.js' {
  declare module.exports: $Exports<'j-toker/test/unit/token-validation'>;
}
declare module 'j-toker/test/unit/update-account.js' {
  declare module.exports: $Exports<'j-toker/test/unit/update-account'>;
}
declare module 'j-toker/test/unit/update-password.js' {
  declare module.exports: $Exports<'j-toker/test/unit/update-password'>;
}
